#!/usr/bin/env python

import wx
import os
import sys
import pdb
import numpy
import threading
import time

title = "DouF00"
numberFontSize = 150

EVT_CLOCK_ID = wx.NewId()

class TriggerClock(wx.PyEvent):
    def __init__(self):
        wx.PyEvent.__init__(self)
        self.SetEventType(EVT_CLOCK_ID)

try:
    basedir = sys.argv[1]
except IndexError:
    basedir = os.getcwd()
    print("No basedir specified, using current directory..")

try:
    os.chdir(basedir)
except OSError:
    print("No such file or directory")
    sys.exit(1)

basedir = os.getcwd()

pictures = []
files = os.listdir(basedir)
for file in files:
    try:
        if (file[-4:].lower() == ".jpg") or (file[-5:].lower() == ".jpeg"):
            pictures.append(file)
    except IndexError:
        pass

pictures.sort()

def loadImage(filename, size, method = "scale"):
    try:
        if filename == "":
            array = numpy.zeros((size[1], size[0], 3), 'uint8')
            image = wx.EmptyImage(size[0], size[1])
            image.SetData(array.tostring())
            bitmap = wx.BitmapFromImage(image)
        else:
            f = open(filename, "rb")
            image = wx.ImageFromStream(f)
            f.close()
            ImageSize = image.GetSize()
            if method == "stretch":
                ImageSize = size
            elif (size[0] < ImageSize[0]) or (size[1] < ImageSize[1]):
                ratioX = float(size[0]) / ImageSize[0]
                ratioY = float(size[1]) / ImageSize[1]
                if ratioX < ratioY:
                    ImageSize[0] = int(ImageSize[0] * ratioX)
                    ImageSize[1] = int(ImageSize[1] * ratioX)
                else:
                    ImageSize[0] = int(ImageSize[0] * ratioY)
                    ImageSize[1] = int(ImageSize[1] * ratioY)
                    
            image.Rescale(ImageSize[0], ImageSize[1])
            bitmap = wx.BitmapFromImage(image)
        return bitmap
    except:
        print("Cant load image")

class PresentationScreen(wx.Frame):
    def __init__(self, displayindex = 0):
        geometry = wx.Display(displayindex).GetGeometry()
        position = (geometry[0], geometry[1])
        self.size = (geometry[2], geometry[3])
        style = wx.NO_BORDER | wx.STAY_ON_TOP
        super(PresentationScreen, self).__init__(None, wx.ID_ANY, title, style = style, pos = position, size = self.size)
        self.box = wx.BoxSizer(wx.VERTICAL)
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.static_bitmap = wx.StaticBitmap(self, wx.ID_ANY)
        self.box.Add(self.static_bitmap, 0, wx.ALIGN_CENTER_HORIZONTAL)
        self.SetSizer(self.box)
    def load(self, filename):
        bitmap = loadImage(filename, self.size)
        self.static_bitmap.SetBitmap(bitmap)

class PresentorsScreen(wx.Frame):
    def __init__(self, displayindex = 0):
        geometry = wx.Display(displayindex).GetGeometry()
        position = (geometry[0], geometry[1])
        self.size = (geometry[2], geometry[3])
        style = wx.NO_BORDER | wx.STAY_ON_TOP
        super(PresentorsScreen, self).__init__(None, wx.ID_ANY, title, style = style, size = self.size, pos = position)
        self.SetBackgroundColour(wx.Colour(127, 127, 127))
        self.static_bitmap1 = wx.StaticBitmap(self, wx.ID_ANY)
        self.static_bitmap2 = wx.StaticBitmap(self, wx.ID_ANY)
        self.hbox = wx.BoxSizer(wx.HORIZONTAL)
        self.hbox.Add(self.static_bitmap1, 99, wx.ALIGN_CENTER_VERTICAL)
        self.hbox.AddStretchSpacer(2)
        self.hbox.Add(self.static_bitmap2, 99, wx.ALIGN_CENTER_VERTICAL)
        self.box = wx.BoxSizer(wx.VERTICAL)
        self.box.Add(self.hbox, 179, wx.ALIGN_CENTER_HORIZONTAL)
        self.box.AddStretchSpacer(1)
        font = wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.BOLD)
        self.hbox2 = wx.BoxSizer(wx.HORIZONTAL)
        self.clock = wx.StaticText(self, wx.ID_ANY, "13:37.0")
        self.clock.SetFont(font)
        self.clockbox = wx.BoxSizer(wx.VERTICAL)
        self.clockbox.Add(self.clock, 0, wx.ALIGN_CENTER_HORIZONTAL)
        self.hbox2.Add(self.clockbox , 2, wx.ALIGN_CENTER_VERTICAL)
        self.hbox2.AddStretchSpacer(1)
        self.countDown = wx.StaticText(self, wx.ID_ANY, "10.0")
        self.countDown.SetFont(font)
        self.countDownbox = wx.BoxSizer(wx.VERTICAL)
        self.countDownbox.Add(self.countDown, 0, wx.ALIGN_CENTER_HORIZONTAL)
        self.hbox2.Add(self.countDownbox , 2, wx.ALIGN_CENTER_VERTICAL)
        self.hbox2.AddStretchSpacer(1)
        self.countUp = wx.StaticText(self, wx.ID_ANY, "0.0")
        self.countUp.SetFont(font)
        self.countUpbox = wx.BoxSizer(wx.VERTICAL)
        self.countUpbox.Add(self.countUp, 0, wx.ALIGN_CENTER_HORIZONTAL)
        self.hbox2.Add(self.countUpbox , 2, wx.ALIGN_CENTER_VERTICAL)
        self.box.Add(self.hbox2, 17, wx.ALIGN_CENTER_HORIZONTAL)

        self.panel = wx.Panel(self, wx.ID_ANY)
        self.panel.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.box.Add(self.panel, 3, wx.EXPAND)

        self.SetSizer(self.box)

    def load(self, filename1, filename2):
        method = "scale"
        if (self.size[0] < 1024) or (self.size[1] < 768):
            method = "stretch"
        width = int(float(self.size[0]) / 200 * 99)
        height = int(float(self.size[1]) / 200 * 179)
        bitmap1 = loadImage(filename1, (width, height), method = method)
        bitmap2 = loadImage(filename2, (width, height), method = method)
        self.static_bitmap1.SetBitmap(bitmap1)
        self.static_bitmap2.SetBitmap(bitmap2)

class NumberFrame(wx.Frame):
    def __init__(self, displayindex):
        geometry = wx.Display(displayindex).GetGeometry()
        style = wx.NO_BORDER | wx.STAY_ON_TOP | wx.FRAME_TOOL_WINDOW
        super(NumberFrame, self).__init__(None, wx.ID_ANY, title, style = style)
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        box = wx.BoxSizer(wx.VERTICAL)
        font = wx.Font(numberFontSize, wx.DEFAULT, wx.NORMAL, wx.BOLD)
        text = wx.StaticText(self, wx.ID_ANY, str(displayindex))
        text.SetFont(font)
        box.Add(text, 0, wx.ALIGN_CENTER)
        self.SetSizerAndFit(box)
        size = self.GetSize()
        position = (geometry[0] + (geometry[2] / 2) - (size[0] / 2),
                    geometry[1] + (geometry[3] / 2) - (size[1] / 2))
        self.SetPosition(position)
        self.Show()

class DisplayChoice(wx.Frame):
    def __init__(self):
        style = wx.DEFAULT_FRAME_STYLE | wx.STAY_ON_TOP
        super(DisplayChoice, self).__init__(None, wx.ID_ANY, title, style = style)
        self.choices = ["-- Nothing --", "Presentation Screen", "Presentors Screen"]
        displays = wx.Display.GetCount()
        box = wx.BoxSizer(wx.VERTICAL)
        self.selections = []
        for d in range(displays):
            choice = wx.Choice(self, wx.ID_ANY, choices = self.choices)
            choice.SetSelection(0)
            self.selections.append(choice)
            hbox = wx.BoxSizer(wx.HORIZONTAL)
            hbox.Add(wx.StaticText(self, wx.ID_ANY, "Display " + str(d) + ": "), 0, wx.ALIGN_CENTER_VERTICAL)
            hbox.Add(choice, 0, wx.ALIGN_CENTER_VERTICAL)
            box.Add(hbox, 0, wx.ALIGN_CENTER_HORIZONTAL)

        self.button = wx.Button(self, wx.ID_ANY, label = "OK")
        box.Add(self.button, 1, wx.ALIGN_CENTER_HORIZONTAL)

        self.SetSizerAndFit(box)
        self.Show()

class MyApp(wx.App):
    def OnInit(self):
        displayCount = wx.Display.GetCount()
        self.numberFrames = []
        for d in range(displayCount):
            self.numberFrames.append(NumberFrame(d))
        self.choice = DisplayChoice()
        self.choice.button.Bind(wx.EVT_BUTTON, self.Run)
        return True

    def OnKeyPress(self, event):
        event.Skip()
        key = event.GetKeyCode()
        if key == wx.WXK_RIGHT:
            self.NextSlide()
        elif key == wx.WXK_LEFT:
            self.PrevSlide()
        elif key == wx.WXK_ESCAPE:
            sys.exit(0)

    def Run(self, event):
        self.slideindex = -1
        displayCount = wx.Display.GetCount()
        self.presentationScreens = []
        self.presentorsScreens = []
        for displayindex in range(displayCount):
            if self.choice.choices[self.choice.selections[displayindex].GetSelection()] == "Presentation Screen":
                self.presentationScreens.append(PresentationScreen(displayindex = displayindex))
            elif self.choice.choices[self.choice.selections[displayindex].GetSelection()] == "Presentors Screen":
                self.presentorsScreens.append(PresentorsScreen(displayindex = displayindex))
        self.choice.Destroy()
        for numberFrame in self.numberFrames:
            numberFrame.Destroy()
        for p in self.presentationScreens:
            p.load("")
            p.Show()
        for p in self.presentorsScreens:
            if len(pictures) != 0:
                p.load("", pictures[0])
            else:
                p.load("", "")
            p.Show()
            p.panel.Bind(wx.EVT_KEY_UP, self.OnKeyPress)
            p.panel.SetFocus()
        self.Clock(self, self.presentorsScreens).start()
        self.Connect(-1, -1, EVT_CLOCK_ID, self.setClock)

    def setClock(self, event):
        t = time.localtime()
        tstr = str(t[3]) + ":" + str(t[4]) + "." + str(t[5])
        for s in self.presentorsScreens:
            s.clock.SetLabel(tstr)

    class Clock(threading.Thread):
        def __init__(self, mainApp, presentorsScreens):
            self.mainApp = mainApp 
            self.presentorsScreens = presentorsScreens
            threading.Thread.__init__(self)
        def run(self):
            while 1:
                wx.PostEvent(self.mainApp, TriggerClock())
                time.sleep(1)


    def NextSlide(self):
        if self.slideindex != len(pictures):
            self.slideindex += 1
        currentSlide = ""
        nextSlide = ""
        if self.slideindex < len(pictures):
            currentSlide = pictures[self.slideindex]
        if self.slideindex + 1 < len(pictures):
            nextSlide = pictures[self.slideindex + 1]
        for p in self.presentationScreens:
            p.load(currentSlide)
            p.Show()
        for p in self.presentorsScreens:
            p.load(currentSlide, nextSlide)
            p.Show()
         
    def PrevSlide(self):
        if self.slideindex != -1:
            self.slideindex -= 1
        currentSlide = ""
        nextSlide = ""
        if -1 < self.slideindex < len(pictures):
            currentSlide = pictures[self.slideindex]
        if self.slideindex + 1 < len(pictures):
            nextSlide = pictures[self.slideindex + 1]
        for p in self.presentationScreens:
            p.load(currentSlide)
            p.Show()
        for p in self.presentorsScreens:
            p.load(currentSlide, nextSlide)
            p.Show()
         

def main():
    app = MyApp()
    app.MainLoop()

if __name__ == "__main__": main()

# vim:nnoremap <silent> <F5> :!./presentation: #
