#!/usr/bin/env python

import wx
import os
import sys
import pdb

title = "DouF00"
numberFontSize = 150

try:
    basedir = sys.argv[1]
except IndexError:
    basedir = os.getcwd()
    print "No basedir specified, using current directory.."

try:
    os.chdir(basedir)
except OSError:
    print "No such file or directory"
    sys.exit(1)

basedir = os.getcwd()

pictures = []
files = os.listdir(basedir)
for file in files:
    try:
        if (file[-4:].lower() == ".jpg") or (file[-5:].lower() == ".jpeg"):
            pictures.append(file)
    except IndexError:
        pass

pictures.sort()
print "\n".join(pictures)

class PresentationScreen(wx.Frame):
    def __init__(self, displayindex = 0):
        geometry = wx.Display(displayindex).GetGeometry()
        position = (geometry[0], geometry[1])
        size = (geometry[2], geometry[3])
        style = wx.NO_BORDER | wx.STAY_ON_TOP
        super(PresentationScreen, self).__init__(None, wx.ID_ANY, title, style = style, pos = position, size = size)
        self.box = wx.BoxSizer(wx.VERTICAL)
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.static_bitmap = wx.StaticBitmap(self, wx.ID_ANY)
        self.box.Add(self.static_bitmap, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.SHAPED)
    def load(self, filename):
        self.filename = filename
        if self.filename == "":
            pass
        try:
            self.f = open(self.filename, "rb")
            self.image = wx.ImageFromStream(self.f)
            ImageSize = self.image.GetSize()
            DisplaySize = wx.DisplaySize()
            if (DisplaySize[0] < ImageSize[0]) or (DisplaySize[1] < ImageSize[1]):
                if (float(DisplaySize[0]) / ImageSize[0]) < (float(DisplaySize[1]) / ImageSize[1]):
                    ImageSize[0] = DisplaySize[0]
                    ImageSize[1] = ImageSize[1] * (DisplaySize[0] / ImageSize[0])
                else:
                    ImageSize[0] = ImageSize[0] * (DisplaySize[1] / ImageSize[1])
                    ImageSize[1] = DisplaySize[1]
                
                self.image.Rescale(ImageSize[0], ImageSize[1])

            self.bitmap = wx.BitmapFromImage(self.image)
            self.static_bitmap.SetBitmap(self.bitmap)
            self.f.close()
        except:
            print "Cant load image"

        self.SetSizer(self.box)
    def Display(self):
        self.Show()

class PresentorsScreen(wx.Frame):
    def __init__(self, displayindex = 0):
        style = wx.NO_BORDER | wx.STAY_ON_TOP
        super(PresentorsScreen, self).__init__(None, wx.ID_ANY, title, style = style, size = (320, 240))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel = wx.Panel(self, wx.ID_ANY)
        self.Show()

class NumberFrame(wx.Frame):
    def __init__(self, displayindex):
        geometry = wx.Display(displayindex).GetGeometry()
        style = wx.NO_BORDER | wx.STAY_ON_TOP | wx.FRAME_TOOL_WINDOW
        super(NumberFrame, self).__init__(None, wx.ID_ANY, title, style = style)
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        box = wx.BoxSizer(wx.VERTICAL)
        font = wx.Font(numberFontSize, wx.DEFAULT, wx.NORMAL, wx.BOLD)
        text = wx.StaticText(self, wx.ID_ANY, str(displayindex))
        text.SetFont(font)
        box.Add(text, 0, wx.ALIGN_CENTER)
        self.SetSizerAndFit(box)
        size = self.GetSize()
        position = (geometry[0] + (geometry[2] / 2) - (size[0] / 2),
                    geometry[1] + (geometry[3] / 2) - (size[1] / 2))
        self.SetPosition(position)
        self.Show()

class DisplayChoice(wx.Frame):
    def __init__(self):
        style = wx.DEFAULT_FRAME_STYLE | wx.STAY_ON_TOP
        super(DisplayChoice, self).__init__(None, wx.ID_ANY, title, style = style)
        self.choices = ["-- Nothing --", "Presentation Screen", "Presentors Screen"]
        displays = wx.Display.GetCount()
        box = wx.BoxSizer(wx.VERTICAL)
        self.selections = []
        for d in range(displays):
            choice = wx.Choice(self, wx.ID_ANY, choices = self.choices)
            choice.SetSelection(0)
            self.selections.append(choice)
            hbox = wx.BoxSizer(wx.HORIZONTAL)
            hbox.Add(wx.StaticText(self, wx.ID_ANY, "Display " + str(d) + ": "), 0, wx.ALIGN_CENTER_VERTICAL)
            hbox.Add(choice, 0, wx.ALIGN_CENTER_VERTICAL)
            box.Add(hbox, 0, wx.ALIGN_CENTER_HORIZONTAL)

        self.button = wx.Button(self, wx.ID_ANY, label = "OK")
        box.Add(self.button, 1, wx.ALIGN_CENTER_HORIZONTAL)

        self.SetSizerAndFit(box)
        self.Show()

class MyApp(wx.App):
    def OnInit(self):
        displayCount = wx.Display.GetCount()
        self.numberFrames = []
        for d in range(displayCount):
            print wx.Display(d).GetGeometry()
            self.numberFrames.append(NumberFrame(d))
        self.choice = DisplayChoice()
        self.choice.button.Bind(wx.EVT_BUTTON, self.Run)
            
        #Beamer = PresentationScreen()
        #Beamer.load("test.jpeg")
        #Beamer.Display()
        #Presentor = PresentorsScreen()
        #Presentor.panel.Bind(wx.EVT_KEY_UP, self.OnKeyPress)
        return True

    def OnKeyPress(self, event):
        pdb.set_trace()
        event.Skip()
        key = event.GetKeyCode()
        if key == ord("f"):
            Beamer.Maximize()

    def LoadImage(self, filename):
        pass

    def Run(self, event):
        displayCount = wx.Display.GetCount()
        self.presentationScreens = []
        self.presentorsScreens = []
        for displayindex in range(displayCount):
            if self.choice.choices[self.choice.selections[displayindex].GetSelection()] == "Presentation Screen":
                self.presentationScreens.append(PresentationScreen(displayindex = displayindex))
            elif self.choice.choices[self.choice.selections[displayindex].GetSelection()] == "Presentors Screen":
                self.presentorsScreens.append(PresentorsScreen(displayindex = displayindex))
        self.choice.Destroy()
        for numberFrame in self.numberFrames:
            numberFrame.Destroy()
        for presentationScreen in self.presentationScreens:
            presentationScreen.Show()


def main():
    app = MyApp()
    app.MainLoop()

if __name__ == "__main__": main()

# vim:nnoremap <silent> <F5> :!./p      resentation: #
