#!/usr/bin/env python

import wx

title = "Presentor"

class PresentationScreen(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, title)
        self.Show(True)
    def display(self, filename):
        self.filename = filename
        self.ShowFullScreen(True)
        self.static_bitmap = wx.StaticBitmap(self, wx.ID_ANY, size=wx.DisplaySize())
        self.f = open(self.filename, "rb")
        self.image = wx.ImageFromStream(self.f)
        self.bitmap = wx.BitmapFromImage(self.image)
        self.static_bitmap.SetBitmap(self.bitmap)
        self.f.close()
        self.Show(True)


app = wx.PySimpleApp()
Beamer = PresentationScreen()
Beamer.display("test.jpeg")
app.MainLoop()

# vim:nnoremap <silent> <F5> :!./presentation: #
