.TH DOUF00 "1" "August 2009" "NiceNameCrew.com" "douf00 presentation software"
.SH NAME
douf00 \- fat free presentations
.SH SYNOPSIS
.B douf00
[\fISlideDir|PDF\fR]
.SH DESCRIPTION
.PP
Douf00 is a lightweight, slim and straight forward Presentation Tool.
.PP
It assists novice as well as expierienced speakers when giving lectures
and buissness meetings. With its simple presentors Screen that includes
current slide - next slide (preview) aswell as timers it is designed
to assist thoose of us, that are willing to step up their lectures
to the next level.

If you place in your presentation directory a file with
the name blank.foo where foo can be: jpeg,jpg,png,bmp or pcx
that will be your blank slide, which shows up when you start douf00.
.SH AUTHORS
Martin Ptacek, <natano@nicenamecrew.com>
.br
Sebastian Maier, <naxx@nicenamecrew.com>
.SH CONTRIBUTORS
Bernd Zeimetz, <bzed@debian.org>
.br
Stefan Heinecke
.br
Josef Philip Bernhart, <bernhartjp@yahoo.de>
.SH "REPORTING BUGS"
Report douf00 bugs to natano@nicenamecrew.com
.br
NiceNameCrew home page: <http://nicenamecrew.com/>
.SH COPYRIGHT
.PP
Copyright (c) 2009  Martin Ptacek
.PP
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
and/or modify it under the terms of the MIT license.
